# Company.destroy_all
# User.destroy_all
# Job.destroy_all
# Profile.destroy_all
# Link.destroy_all
# Evaluation.destroy_all
# Token.destroy_all


# All sample candidates
User.create(first_name: "Ethan", last_name: "Fertsch", email: "efertsch@gmail.com", password: "password")
User.create(first_name: "Davison", last_name: "Bare", email: "davis@mail.com", password: "password")
User.create(first_name: "Kimberly", last_name: "Embry", email: "kim@mail.com", password: "password")
User.create(first_name: "Brian", last_name: "Bernheim", email: "brian@mail.com", password: "password")
User.create(first_name: "Jack", last_name: "Howerton", email: "jack@mail.com", password: "password")

# User that works for a company aka HR rep.
User.create(first_name: "test", last_name: "test", email: "test", password: "test", company_id: 1)


#All sample Profiles
Profile.create(location: "Greater Boston Area", objective: "Get a job building beautiful and meaningful things", summary: "My name is Ethan and I love dogs.", user_id: 1)
Profile.create(location: "San Francisco Bay Area", objective: "Get a job building beautiful and meaningful things", summary: "My name is Davis and I love pizza.", user_id: 2)
Profile.create(location: "San Francisco Bay Area", objective: "Get a job building beautiful and meaningful things", summary: "My name is Kim and I love looking on fleek at all times.", user_id: 3)
Profile.create(location: "San Francisco Bay Area", objective: "Get a job building beautiful and meaningful things", summary: "My name is Jack and I love wearing flip flops in March. ", user_id: 4)
Profile.create(location: "San Francisco Bay Area", objective: "Get a job building beautiful and meaningful things", summary: "My name is Brian and I love the word 'chill'", user_id: 5)



# All sample companies
Company.create(name: "Google", email: "google@gmail.com", location: "1600 Amphitheatre Pkwy, Mountain View, CA 94043")
Company.create(name: "Apple", email: "apple@apple.com", location: "1 Infinite Loop, Cupertino, CA 95014")
Company.create(name: "LinkedIn", email: "linkedin@mail.com", location: "2029 Stierlin Court Suite 200, Mountain View, CA 94043")
Company.create(name: "Pinterest", email: "pinterest@mail.com", location: "808 Brannan Street, San Francisco, CA 94103")
Company.create(name: "DreamHost", email: "swo@mail.com", location: "1847 Bailey Parks, Joeymouth, Wyoming 96527")
Company.create(name: "Slack", email: "slack@mail.com", location: "155 5th Street, San Francisco, CA 94103")
Company.create(name: "Shopify", email: "shopify@mail.com", location: "150 Elgin Street, 8th Floor Ottawa, ON, Canada K2P 1L4")
Company.create(name: "ZipCar", email: "zipcar@mail.com", location: "35 Thomson Pl, Boston, MA 02210")
Company.create(name: "Salesforce", email: "salesforce@mail.com", location: "The Landmark @ One Market Suite 300, San Francisco, CA 94105")
Company.create(name: "Stripe", email: "stripe@mail.com", location: "185 Berry Street Suite 550, San Francisco, CA 94107")





# All sample jobs

# Jobs posted from company 1
Job.create(position: "Software Engineer", location: "San Francisco, CA", description: "As our transactional volume grows, our systems have to be re-architected to relieve bottlenecks. As our codebase and number of engineers grow, we invest in better tools so that we remain agile. The following experience is relevant to us: Ruby-on-Rails or Java in a production environment. Scaling high-traffic web applications (architecture/database/memcache/CDN). Server administration and Amazon Web Services (EC2 et al.). Performance benchmarking and diagnostic tools. Web service design.", company_id: 1, compensation: "108,000/year", job_type:"full-time")

Job.create(position: "Software Engineering Intern", location: "Austin, Texas", description: "You are a web developer with mad coding skills, who can build innovative applications fast and with high quality. You know Ruby on Rails inside out and actively follow the Rails community. You are excellent full stack programmer: from Backbone.js and Bootrstrap to PostgreSQL and Redis. You can take ownership of a feature from idea to production, with minimal guidance and supervision. You want to have fun at work, you love working with a smart and talented team, and you aren’t afraid to speak up and make yourself heard. What You’ll Do: Work in a highly agile team of talented Rails and Javascript engineers. Build amazing web apps that delight users every day. Work with product, business, and design teams to push the bar higher every day. Write tests. Write code. Deploy. Measure. Rinse and repeat!", company_id: 1, compensation: "$40/hour", job_type:"internship")

Job.create(position: "Front End Web Developer", location: "Remote", description: "In this position you will be a part of the Global Marketing Communications team, reporting to the Online Manager. You will use ninja like graphical and UX skills create the best experience possible for our users. You will implement these by using your unmatched HTML, HTML5 and CSS skills. The ideal candidate has a portfolio that demonstrates skills in designing and implementing user-centric websites and web-applications. You will liaise with Marketing & Communications, and other stakeholders in Unity, to execute visually-stunning, intuitive, and world class web design and applications for our global audiences. You’re an organized creative and highly technical person who enjoys working with people and game engine technology in equal measure. You love having lots of conversations at the same time, but never lose sight of your priorities. Your positive attitude helps you work in an international team with maturity, independence, and diplomacy. Helping people create amazing games, either through direct assistance or useful content, motivates you to keep improving your skillset. You are equally comfortable talking to customers and working with internal engineering teams to troubleshoot problems. You have knowledge of C# and are passionate about console games.", company_id: 1, compensation: "$56/hour", job_type:"freelance")

Job.create(position: "Full Stack Web Developer", location: "San Francisco, CA", description: "Chargebacks, fraud, account takeovers — these are some of the most stressful experiences a seller can deal with. At Square, we believe we can improve on the financial industry’s status quo for managing risk, and find better ways to help and protect our sellers. We’ve launched programs like Chargeback Protection that are unique in the payments industry, and we’re developing tools to help sellers understand risks to their business at a glance. As a software engineer on Disputes and Risk Experience, you will be responsible for designing and building the services that sellers interact with on a daily basis to manage disputes and act on suspicious account activity. You’ll also work on internal tools and infrastructure to help Square manage risk. You will build beautiful web applications, design highly available services, and work with complex distributed systems. If you love delivering software that improves the lives of business owners, we want to work with you!", company_id: 1, compensation: "$115,000/year", job_type:"part-time")

#Jobs posted from company 2
Job.create(position: "Software Developer", location: "Chicago, Illinois", description: "As our transactional volume grows, our systems have to be re-architected to relieve bottlenecks. As our codebase and number of engineers grow, we invest in better tools so that we remain agile. The following experience is relevant to us: Ruby-on-Rails or Java in a production environment. Scaling high-traffic web applications (architecture/database/memcache/CDN). Server administration and Amazon Web Services (EC2 et al.). Performance benchmarking and diagnostic tools. Web service design.", company_id: 2, compensation: "$96,000/year", job_type:"full-time")

Job.create(position: "Software Developer", location: "Boston, Massachusetts", description: "You are a web developer with mad coding skills, who can build innovative applications fast and with high quality. You know Ruby on Rails inside out and actively follow the Rails community. You are excellent full stack programmer: from Backbone.js and Bootrstrap to PostgreSQL and Redis. You can take ownership of a feature from idea to production, with minimal guidance and supervision. You want to have fun at work, you love working with a smart and talented team, and you aren’t afraid to speak up and make yourself heard. What You’ll Do: Work in a highly agile team of talented Rails and Javascript engineers. Build amazing web apps that delight users every day. Work with product, business, and design teams to push the bar higher every day. Write tests. Write code. Deploy. Measure. Rinse and repeat!", company_id: 2, compensation: "$55/hour", job_type:"internship")

Job.create(position: "Back End Web Developer", location: "Remote", description: "In this position you will be a part of the Global Marketing Communications team, reporting to the Online Manager. You will use ninja like graphical and UX skills create the best experience possible for our users. You will implement these by using your unmatched HTML, HTML5 and CSS skills. The ideal candidate has a portfolio that demonstrates skills in designing and implementing user-centric websites and web-applications. You will liaise with Marketing & Communications, and other stakeholders in Unity, to execute visually-stunning, intuitive, and world class web design and applications for our global audiences. You’re an organized creative and highly technical person who enjoys working with people and game engine technology in equal measure. You love having lots of conversations at the same time, but never lose sight of your priorities. Your positive attitude helps you work in an international team with maturity, independence, and diplomacy. Helping people create amazing games, either through direct assistance or useful content, motivates you to keep improving your skillset. You are equally comfortable talking to customers and working with internal engineering teams to troubleshoot problems. You have knowledge of C# and are passionate about console games.", company_id: 2, compensation: "$60/hour", job_type:"freelance")

Job.create(position: "Full Stack Software Engineer", location: "Seattle, Washington", description: "Chargebacks, fraud, account takeovers — these are some of the most stressful experiences a seller can deal with. At Square, we believe we can improve on the financial industry’s status quo for managing risk, and find better ways to help and protect our sellers. We’ve launched programs like Chargeback Protection that are unique in the payments industry, and we’re developing tools to help sellers understand risks to their business at a glance. As a software engineer on Disputes and Risk Experience, you will be responsible for designing and building the services that sellers interact with on a daily basis to manage disputes and act on suspicious account activity. You’ll also work on internal tools and infrastructure to help Square manage risk. You will build beautiful web applications, design highly available services, and work with complex distributed systems. If you love delivering software that improves the lives of business owners, we want to work with you!", company_id: 2, compensation: "$56/hour", job_type:"part-time")

# #Jobs posted from company 3
Job.create(position: "Software Engineer", location: "Portland, Oregon", description: "As our transactional volume grows, our systems have to be re-architected to relieve bottlenecks. As our codebase and number of engineers grow, we invest in better tools so that we remain agile. The following experience is relevant to us: Ruby-on-Rails or Java in a production environment. Scaling high-traffic web applications (architecture/database/memcache/CDN). Server administration and Amazon Web Services (EC2 et al.). Performance benchmarking and diagnostic tools. Web service design.", company_id: 3, compensation: "$96,000/year", job_type:"full-time")

Job.create(position: "Software Developer Intern", location: "Los Angeles, CA", description: "You are a web developer with mad coding skills, who can build innovative applications fast and with high quality. You know Ruby on Rails inside out and actively follow the Rails community. You are excellent full stack programmer: from Backbone.js and Bootrstrap to PostgreSQL and Redis. You can take ownership of a feature from idea to production, with minimal guidance and supervision. You want to have fun at work, you love working with a smart and talented team, and you aren’t afraid to speak up and make yourself heard. What You’ll Do: Work in a highly agile team of talented Rails and Javascript engineers. Build amazing web apps that delight users every day. Work with product, business, and design teams to push the bar higher every day. Write tests. Write code. Deploy. Measure. Rinse and repeat!", company_id: 3, compensation: "$45/hour", job_type:"internship")

Job.create(position: "Front End Web Developer", location: "Remote", description: "In this position you will be a part of the Global Marketing Communications team, reporting to the Online Manager. You will use ninja like graphical and UX skills create the best experience possible for our users. You will implement these by using your unmatched HTML, HTML5 and CSS skills. The ideal candidate has a portfolio that demonstrates skills in designing and implementing user-centric websites and web-applications. You will liaise with Marketing & Communications, and other stakeholders in Unity, to execute visually-stunning, intuitive, and world class web design and applications for our global audiences. You’re an organized creative and highly technical person who enjoys working with people and game engine technology in equal measure. You love having lots of conversations at the same time, but never lose sight of your priorities. Your positive attitude helps you work in an international team with maturity, independence, and diplomacy. Helping people create amazing games, either through direct assistance or useful content, motivates you to keep improving your skillset. You are equally comfortable talking to customers and working with internal engineering teams to troubleshoot problems. You have knowledge of C# and are passionate about console games.", company_id: 3, compensation: "$76/hour", job_type:"freelance")

Job.create(position: "Full Stack Engineer", location: "San Francisco, CA", description: "Chargebacks, fraud, account takeovers — these are some of the most stressful experiences a seller can deal with. At Square, we believe we can improve on the financial industry’s status quo for managing risk, and find better ways to help and protect our sellers. We’ve launched programs like Chargeback Protection that are unique in the payments industry, and we’re developing tools to help sellers understand risks to their business at a glance. As a software engineer on Disputes and Risk Experience, you will be responsible for designing and building the services that sellers interact with on a daily basis to manage disputes and act on suspicious account activity. You’ll also work on internal tools and infrastructure to help Square manage risk. You will build beautiful web applications, design highly available services, and work with complex distributed systems. If you love delivering software that improves the lives of business owners, we want to work with you!", company_id: 3, compensation: "$108,000", job_type:"part-time")

# #Jobs posted from company 4
Job.create(position: "Software Engineer", location: "San Francisco, CA", description: "As our transactional volume grows, our systems have to be re-architected to relieve bottlenecks. As our codebase and number of engineers grow, we invest in better tools so that we remain agile. The following experience is relevant to us: Ruby-on-Rails or Java in a production environment. Scaling high-traffic web applications (architecture/database/memcache/CDN). Server administration and Amazon Web Services (EC2 et al.). Performance benchmarking and diagnostic tools. Web service design.", company_id: 4, compensation: "$135,000/year", job_type:"full-time")

Job.create(position: "Web Developer Intern", location: "New York, New York", description: "You are a web developer with mad coding skills, who can build innovative applications fast and with high quality. You know Ruby on Rails inside out and actively follow the Rails community. You are excellent full stack programmer: from Backbone.js and Bootrstrap to PostgreSQL and Redis. You can take ownership of a feature from idea to production, with minimal guidance and supervision. You want to have fun at work, you love working with a smart and talented team, and you aren’t afraid to speak up and make yourself heard. What You’ll Do: Work in a highly agile team of talented Rails and Javascript engineers. Build amazing web apps that delight users every day. Work with product, business, and design teams to push the bar higher every day. Write tests. Write code. Deploy. Measure. Rinse and repeat!", company_id: 4, compensation: "$45/hour", job_type:"internship")

Job.create(position: "Front End Web Developer", location: "Seattle, Washington", description: "In this position you will be a part of the Global Marketing Communications team, reporting to the Online Manager. You will use ninja like graphical and UX skills create the best experience possible for our users. You will implement these by using your unmatched HTML, HTML5 and CSS skills. The ideal candidate has a portfolio that demonstrates skills in designing and implementing user-centric websites and web-applications. You will liaise with Marketing & Communications, and other stakeholders in Unity, to execute visually-stunning, intuitive, and world class web design and applications for our global audiences. You’re an organized creative and highly technical person who enjoys working with people and game engine technology in equal measure. You love having lots of conversations at the same time, but never lose sight of your priorities. Your positive attitude helps you work in an international team with maturity, independence, and diplomacy. Helping people create amazing games, either through direct assistance or useful content, motivates you to keep improving your skillset. You are equally comfortable talking to customers and working with internal engineering teams to troubleshoot problems. You have knowledge of C# and are passionate about console games.", company_id: 4, compensation: "$76/hour", job_type:"freelance")

Job.create(position: "Back End Software Engineer", location: "Atlanta, Georgia", description: "Chargebacks, fraud, account takeovers — these are some of the most stressful experiences a seller can deal with. At Square, we believe we can improve on the financial industry’s status quo for managing risk, and find better ways to help and protect our sellers. We’ve launched programs like Chargeback Protection that are unique in the payments industry, and we’re developing tools to help sellers understand risks to their business at a glance. As a software engineer on Disputes and Risk Experience, you will be responsible for designing and building the services that sellers interact with on a daily basis to manage disputes and act on suspicious account activity. You’ll also work on internal tools and infrastructure to help Square manage risk. You will build beautiful web applications, design highly available services, and work with complex distributed systems. If you love delivering software that improves the lives of business owners, we want to work with you!", company_id: 4, compensation: "$65/hour", job_type:"part-time")

# #Jobs posted from company 5
Job.create(position: "Software Engineer", location: "San Jose, CA", description: "As our transactional volume grows, our systems have to be re-architected to relieve bottlenecks. As our codebase and number of engineers grow, we invest in better tools so that we remain agile. The following experience is relevant to us: Ruby-on-Rails or Java in a production environment. Scaling high-traffic web applications (architecture/database/memcache/CDN). Server administration and Amazon Web Services (EC2 et al.). Performance benchmarking and diagnostic tools. Web service design.", company_id: 5, compensation: "$96,000/year", job_type:"full-time")

Job.create(position: "Software Engineering Intern", location: "Austin, Texas", description: "You are a web developer with mad coding skills, who can build innovative applications fast and with high quality. You know Ruby on Rails inside out and actively follow the Rails community. You are excellent full stack programmer: from Backbone.js and Bootrstrap to PostgreSQL and Redis. You can take ownership of a feature from idea to production, with minimal guidance and supervision. You want to have fun at work, you love working with a smart and talented team, and you aren’t afraid to speak up and make yourself heard. What You’ll Do: Work in a highly agile team of talented Rails and Javascript engineers. Build amazing web apps that delight users every day. Work with product, business, and design teams to push the bar higher every day. Write tests. Write code. Deploy. Measure. Rinse and repeat!", company_id: 5, compensation: "$45/hour", job_type:"internship")

Job.create(position: "Front End Web Developer", location: "Portland, Oregon", description: "In this position you will be a part of the Global Marketing Communications team, reporting to the Online Manager. You will use ninja like graphical and UX skills create the best experience possible for our users. You will implement these by using your unmatched HTML, HTML5 and CSS skills. The ideal candidate has a portfolio that demonstrates skills in designing and implementing user-centric websites and web-applications. You will liaise with Marketing & Communications, and other stakeholders in Unity, to execute visually-stunning, intuitive, and world class web design and applications for our global audiences. You’re an organized creative and highly technical person who enjoys working with people and game engine technology in equal measure. You love having lots of conversations at the same time, but never lose sight of your priorities. Your positive attitude helps you work in an international team with maturity, independence, and diplomacy. Helping people create amazing games, either through direct assistance or useful content, motivates you to keep improving your skillset. You are equally comfortable talking to customers and working with internal engineering teams to troubleshoot problems. You have knowledge of C# and are passionate about console games.", company_id: 5, compensation: "$76/hour", job_type:"freelance")

Job.create(position: "Full Stack Software Engineer", location: "Boston, Massachusetts", description: "Chargebacks, fraud, account takeovers — these are some of the most stressful experiences a seller can deal with. At Square, we believe we can improve on the financial industry’s status quo for managing risk, and find better ways to help and protect our sellers. We’ve launched programs like Chargeback Protection that are unique in the payments industry, and we’re developing tools to help sellers understand risks to their business at a glance. As a software engineer on Disputes and Risk Experience, you will be responsible for designing and building the services that sellers interact with on a daily basis to manage disputes and act on suspicious account activity. You’ll also work on internal tools and infrastructure to help Square manage risk. You will build beautiful web applications, design highly available services, and work with complex distributed systems. If you love delivering software that improves the lives of business owners, we want to work with you!", company_id: 5, compensation: "$65/hour", job_type:"part-time")

# #Jobs posted from company 6
Job.create(position: "Software Engineer, Systems & Infrastructure", location: "San Jose, CA", description: "As our transactional volume grows, our systems have to be re-architected to relieve bottlenecks. As our codebase and number of engineers grow, we invest in better tools so that we remain agile. The following experience is relevant to us: Ruby-on-Rails or Java in a production environment. Scaling high-traffic web applications (architecture/database/memcache/CDN). Server administration and Amazon Web Services (EC2 et al.). Performance benchmarking and diagnostic tools. Web service design.", company_id: 6, compensation: "96,000", job_type:"full-time")

Job.create(position: "Software Engineering Intern", location: "Chicago, Illinois", description: "You are a web developer with mad coding skills, who can build innovative applications fast and with high quality. You know Ruby on Rails inside out and actively follow the Rails community. You are excellent full stack programmer: from Backbone.js and Bootrstrap to PostgreSQL and Redis. You can take ownership of a feature from idea to production, with minimal guidance and supervision. You want to have fun at work, you love working with a smart and talented team, and you aren’t afraid to speak up and make yourself heard. What You’ll Do: Work in a highly agile team of talented Rails and Javascript engineers. Build amazing web apps that delight users every day. Work with product, business, and design teams to push the bar higher every day. Write tests. Write code. Deploy. Measure. Rinse and repeat!", company_id: 6, compensation: "$45/hour", job_type:"internship")

Job.create(position: "Front End Web Developer", location: "Remote", description: "In this position you will be a part of the Global Marketing Communications team, reporting to the Online Manager. You will use ninja like graphical and UX skills create the best experience possible for our users. You will implement these by using your unmatched HTML, HTML5 and CSS skills. The ideal candidate has a portfolio that demonstrates skills in designing and implementing user-centric websites and web-applications. You will liaise with Marketing & Communications, and other stakeholders in Unity, to execute visually-stunning, intuitive, and world class web design and applications for our global audiences. You’re an organized creative and highly technical person who enjoys working with people and game engine technology in equal measure. You love having lots of conversations at the same time, but never lose sight of your priorities. Your positive attitude helps you work in an international team with maturity, independence, and diplomacy. Helping people create amazing games, either through direct assistance or useful content, motivates you to keep improving your skillset. You are equally comfortable talking to customers and working with internal engineering teams to troubleshoot problems. You have knowledge of C# and are passionate about console games.", company_id: 6, compensation: "$45/hour", job_type:"freelance")

Job.create(position: "Full Stack Software Engineer", location: "New York, New York", description: "Chargebacks, fraud, account takeovers — these are some of the most stressful experiences a seller can deal with. At Square, we believe we can improve on the financial industry’s status quo for managing risk, and find better ways to help and protect our sellers. We’ve launched programs like Chargeback Protection that are unique in the payments industry, and we’re developing tools to help sellers understand risks to their business at a glance. As a software engineer on Disputes and Risk Experience, you will be responsible for designing and building the services that sellers interact with on a daily basis to manage disputes and act on suspicious account activity. You’ll also work on internal tools and infrastructure to help Square manage risk. You will build beautiful web applications, design highly available services, and work with complex distributed systems. If you love delivering software that improves the lives of business owners, we want to work with you!", company_id: 6, compensation: "$75/hour", job_type:"part-time")

# #Jobs posted from company 7
Job.create(position: "Software Engineer, Systems & Infrastructure", location: "San Francisco, CA", description: "As our transactional volume grows, our systems have to be re-architected to relieve bottlenecks. As our codebase and number of engineers grow, we invest in better tools so that we remain agile. The following experience is relevant to us: Ruby-on-Rails or Java in a production environment. Scaling high-traffic web applications (architecture/database/memcache/CDN). Server administration and Amazon Web Services (EC2 et al.). Performance benchmarking and diagnostic tools. Web service design.", company_id: 7, compensation: "$88,000/year", job_type:"full-time")

Job.create(position: "Software Engineering Intern", location: "Seattle, Washington", description: "You are a web developer with mad coding skills, who can build innovative applications fast and with high quality. You know Ruby on Rails inside out and actively follow the Rails community. You are excellent full stack programmer: from Backbone.js and Bootrstrap to PostgreSQL and Redis. You can take ownership of a feature from idea to production, with minimal guidance and supervision. You want to have fun at work, you love working with a smart and talented team, and you aren’t afraid to speak up and make yourself heard. What You’ll Do: Work in a highly agile team of talented Rails and Javascript engineers. Build amazing web apps that delight users every day. Work with product, business, and design teams to push the bar higher every day. Write tests. Write code. Deploy. Measure. Rinse and repeat!", company_id: 7, compensation: "$45/hour", job_type:"internship")

Job.create(position: "Front End Web Developer", location: "Chicago, Illinois", description: "In this position you will be a part of the Global Marketing Communications team, reporting to the Online Manager. You will use ninja like graphical and UX skills create the best experience possible for our users. You will implement these by using your unmatched HTML, HTML5 and CSS skills. The ideal candidate has a portfolio that demonstrates skills in designing and implementing user-centric websites and web-applications. You will liaise with Marketing & Communications, and other stakeholders in Unity, to execute visually-stunning, intuitive, and world class web design and applications for our global audiences. You’re an organized creative and highly technical person who enjoys working with people and game engine technology in equal measure. You love having lots of conversations at the same time, but never lose sight of your priorities. Your positive attitude helps you work in an international team with maturity, independence, and diplomacy. Helping people create amazing games, either through direct assistance or useful content, motivates you to keep improving your skillset. You are equally comfortable talking to customers and working with internal engineering teams to troubleshoot problems. You have knowledge of C# and are passionate about console games.", company_id: 7, compensation: "$45/hour", job_type:"freelance")

Job.create(position: "Full Stack Software Engineer", location: "San Francisco, CA", description: "Chargebacks, fraud, account takeovers — these are some of the most stressful experiences a seller can deal with. At Square, we believe we can improve on the financial industry’s status quo for managing risk, and find better ways to help and protect our sellers. We’ve launched programs like Chargeback Protection that are unique in the payments industry, and we’re developing tools to help sellers understand risks to their business at a glance. As a software engineer on Disputes and Risk Experience, you will be responsible for designing and building the services that sellers interact with on a daily basis to manage disputes and act on suspicious account activity. You’ll also work on internal tools and infrastructure to help Square manage risk. You will build beautiful web applications, design highly available services, and work with complex distributed systems. If you love delivering software that improves the lives of business owners, we want to work with you!", company_id: 7, compensation: "$55/hour", job_type:"part-time")

# #Jobs posted from company 8
Job.create(position: "Software Engineer, Systems & Infrastructure", location: "San Francisco, CA", description: "As our transactional volume grows, our systems have to be re-architected to relieve bottlenecks. As our codebase and number of engineers grow, we invest in better tools so that we remain agile. The following experience is relevant to us: Ruby-on-Rails or Java in a production environment. Scaling high-traffic web applications (architecture/database/memcache/CDN). Server administration and Amazon Web Services (EC2 et al.). Performance benchmarking and diagnostic tools. Web service design.", company_id: 8, compensation: "$108,000", job_type:"full-time")

Job.create(position: "Software Engineering Intern", location: "Austin, Texas", description: "You are a web developer with mad coding skills, who can build innovative applications fast and with high quality. You know Ruby on Rails inside out and actively follow the Rails community. You are excellent full stack programmer: from Backbone.js and Bootrstrap to PostgreSQL and Redis. You can take ownership of a feature from idea to production, with minimal guidance and supervision. You want to have fun at work, you love working with a smart and talented team, and you aren’t afraid to speak up and make yourself heard. What You’ll Do: Work in a highly agile team of talented Rails and Javascript engineers. Build amazing web apps that delight users every day. Work with product, business, and design teams to push the bar higher every day. Write tests. Write code. Deploy. Measure. Rinse and repeat!", company_id: 8, compensation: "$40/hour", job_type:"internship")

Job.create(position: "Front End Web Developer", location: "Remote", description: "In this position you will be a part of the Global Marketing Communications team, reporting to the Online Manager. You will use ninja like graphical and UX skills create the best experience possible for our users. You will implement these by using your unmatched HTML, HTML5 and CSS skills. The ideal candidate has a portfolio that demonstrates skills in designing and implementing user-centric websites and web-applications. You will liaise with Marketing & Communications, and other stakeholders in Unity, to execute visually-stunning, intuitive, and world class web design and applications for our global audiences. You’re an organized creative and highly technical person who enjoys working with people and game engine technology in equal measure. You love having lots of conversations at the same time, but never lose sight of your priorities. Your positive attitude helps you work in an international team with maturity, independence, and diplomacy. Helping people create amazing games, either through direct assistance or useful content, motivates you to keep improving your skillset. You are equally comfortable talking to customers and working with internal engineering teams to troubleshoot problems. You have knowledge of C# and are passionate about console games.", company_id: 8, compensation: "$60/hour", job_type:"freelance")

Job.create(position: "Full Stack Software Engineer", location: "Boston, Massachusetts", description: "Chargebacks, fraud, account takeovers — these are some of the most stressful experiences a seller can deal with. At Square, we believe we can improve on the financial industry’s status quo for managing risk, and find better ways to help and protect our sellers. We’ve launched programs like Chargeback Protection that are unique in the payments industry, and we’re developing tools to help sellers understand risks to their business at a glance. As a software engineer on Disputes and Risk Experience, you will be responsible for designing and building the services that sellers interact with on a daily basis to manage disputes and act on suspicious account activity. You’ll also work on internal tools and infrastructure to help Square manage risk. You will build beautiful web applications, design highly available services, and work with complex distributed systems. If you love delivering software that improves the lives of business owners, we want to work with you!", company_id: 8, compensation: "$65/hour", job_type:"part-time")

# Jobs posted from company 9
Job.create(position: "Software Engineer, Systems & Infrastructure", location: "San Francisco, CA", description: "As our transactional volume grows, our systems have to be re-architected to relieve bottlenecks. As our codebase and number of engineers grow, we invest in better tools so that we remain agile. The following experience is relevant to us: Ruby-on-Rails or Java in a production environment. Scaling high-traffic web applications (architecture/database/memcache/CDN). Server administration and Amazon Web Services (EC2 et al.). Performance benchmarking and diagnostic tools. Web service design.", company_id: 9, compensation: "$115,000/year", job_type:"full-time")

Job.create(position: "Software Engineering Intern", location: "Remote", description: "You are a web developer with mad coding skills, who can build innovative applications fast and with high quality. You know Ruby on Rails inside out and actively follow the Rails community. You are excellent full stack programmer: from Backbone.js and Bootrstrap to PostgreSQL and Redis. You can take ownership of a feature from idea to production, with minimal guidance and supervision. You want to have fun at work, you love working with a smart and talented team, and you aren’t afraid to speak up and make yourself heard. What You’ll Do: Work in a highly agile team of talented Rails and Javascript engineers. Build amazing web apps that delight users every day. Work with product, business, and design teams to push the bar higher every day. Write tests. Write code. Deploy. Measure. Rinse and repeat!", company_id: 9, compensation: "$45/hour", job_type:"internship")

Job.create(position: "Front End Web Developer", location: "Seattle, Washington", description: "In this position you will be a part of the Global Marketing Communications team, reporting to the Online Manager. You will use ninja like graphical and UX skills create the best experience possible for our users. You will implement these by using your unmatched HTML, HTML5 and CSS skills. The ideal candidate has a portfolio that demonstrates skills in designing and implementing user-centric websites and web-applications. You will liaise with Marketing & Communications, and other stakeholders in Unity, to execute visually-stunning, intuitive, and world class web design and applications for our global audiences. You’re an organized creative and highly technical person who enjoys working with people and game engine technology in equal measure. You love having lots of conversations at the same time, but never lose sight of your priorities. Your positive attitude helps you work in an international team with maturity, independence, and diplomacy. Helping people create amazing games, either through direct assistance or useful content, motivates you to keep improving your skillset. You are equally comfortable talking to customers and working with internal engineering teams to troubleshoot problems. You have knowledge of C# and are passionate about console games.", company_id: 9, compensation: "$70/hour", job_type:"freelance")

Job.create(position: "Full Stack Software Engineer", location: "New York, New York", description: "Chargebacks, fraud, account takeovers — these are some of the most stressful experiences a seller can deal with. At Square, we believe we can improve on the financial industry’s status quo for managing risk, and find better ways to help and protect our sellers. We’ve launched programs like Chargeback Protection that are unique in the payments industry, and we’re developing tools to help sellers understand risks to their business at a glance. As a software engineer on Disputes and Risk Experience, you will be responsible for designing and building the services that sellers interact with on a daily basis to manage disputes and act on suspicious account activity. You’ll also work on internal tools and infrastructure to help Square manage risk. You will build beautiful web applications, design highly available services, and work with complex distributed systems. If you love delivering software that improves the lives of business owners, we want to work with you!", company_id: 9, compensation: "$125,000/year", job_type:"part-time")

# #Jobs posted from company 10
Job.create(position: "Software Engineer, Systems & Infrastructure", location: "Boston, Massachusetts", description: "As our transactional volume grows, our systems have to be re-architected to relieve bottlenecks. As our codebase and number of engineers grow, we invest in better tools so that we remain agile. The following experience is relevant to us: Ruby-on-Rails or Java in a production environment. Scaling high-traffic web applications (architecture/database/memcache/CDN). Server administration and Amazon Web Services (EC2 et al.). Performance benchmarking and diagnostic tools. Web service design.", company_id: 10, compensation: "$96,000", job_type:"full-time")

Job.create(position: "Software Engineering Intern", location: "New York, New York", description: "You are a web developer with mad coding skills, who can build innovative applications fast and with high quality. You know Ruby on Rails inside out and actively follow the Rails community. You are excellent full stack programmer: from Backbone.js and Bootrstrap to PostgreSQL and Redis. You can take ownership of a feature from idea to production, with minimal guidance and supervision. You want to have fun at work, you love working with a smart and talented team, and you aren’t afraid to speak up and make yourself heard. What You’ll Do: Work in a highly agile team of talented Rails and Javascript engineers. Build amazing web apps that delight users every day. Work with product, business, and design teams to push the bar higher every day. Write tests. Write code. Deploy. Measure. Rinse and repeat!", company_id: 10, compensation: "$55/hour", job_type:"internship")

Job.create(position: "Front End Web Developer", location: "Los Angeles, CA", description: "In this position you will be a part of the Global Marketing Communications team, reporting to the Online Manager. You will use ninja like graphical and UX skills create the best experience possible for our users. You will implement these by using your unmatched HTML, HTML5 and CSS skills. The ideal candidate has a portfolio that demonstrates skills in designing and implementing user-centric websites and web-applications. You will liaise with Marketing & Communications, and other stakeholders in Unity, to execute visually-stunning, intuitive, and world class web design and applications for our global audiences. You’re an organized creative and highly technical person who enjoys working with people and game engine technology in equal measure. You love having lots of conversations at the same time, but never lose sight of your priorities. Your positive attitude helps you work in an international team with maturity, independence, and diplomacy. Helping people create amazing games, either through direct assistance or useful content, motivates you to keep improving your skillset. You are equally comfortable talking to customers and working with internal engineering teams to troubleshoot problems. You have knowledge of C# and are passionate about console games.", company_id: 10, compensation: "$76/hour", job_type:"freelance")

Job.create(position: "Full Stack Software Engineer", location: "Austin, Texas", description: "Chargebacks, fraud, account takeovers — these are some of the most stressful experiences a seller can deal with. At Square, we believe we can improve on the financial industry’s status quo for managing risk, and find better ways to help and protect our sellers. We’ve launched programs like Chargeback Protection that are unique in the payments industry, and we’re developing tools to help sellers understand risks to their business at a glance. As a software engineer on Disputes and Risk Experience, you will be responsible for designing and building the services that sellers interact with on a daily basis to manage disputes and act on suspicious account activity. You’ll also work on internal tools and infrastructure to help Square manage risk. You will build beautiful web applications, design highly available services, and work with complex distributed systems. If you love delivering software that improves the lives of business owners, we want to work with you!", company_id: 10, compensation: "$65/hour", job_type:"part-time")



# All Sample Links

#GitHub
Link.create(link_type: "Github", url: "https://github.com/efertsch", description: "Link to Gituhb" , user_id: 1)
Link.create(link_type: "Github", url: "https://github.com/dbare", description: "Link to Gituhb", user_id: 2)
Link.create(link_type: "Github", url: "https://github.com/kimberlyjoyceembry", description: "Link to Gituhb" , user_id: 3)
Link.create(link_type: "Github", url: "https://github.com/jackhowerton", description: "Link to Gituhb" , user_id: 4)
Link.create(link_type: "Github", url: "https://github.com/btbernheim", description: "Link to Gituhb", user_id: 5)

#LinkedIn
Link.create(link_type: "LinkedIn", url: "https://www.linkedin.com/in/ethan-fertsch/", description: "Link to LinkedIn", user_id: 1)
Link.create(link_type: "LinkedIn", url: "https://www.linkedin.com/in/davis-bare/", description: "Link to LinkedIn", user_id: 2)
Link.create(link_type: "LinkedIn", url: "https://www.linkedin.com/in/kimberly-embry-53346388/", description: "Link to LinkedIn", user_id: 3)
Link.create(link_type: "LinkedIn", url: "https://www.linkedin.com/in/jackhowerton/", description: "Link to LinkedIn", user_id: 4)
Link.create(link_type: "LinkedIn", url: "https://www.linkedin.com/in/brian-bernheim-67381665/", description: "Link to LinkedIn", user_id: 5)



#All Sample Evaluations
Evaluation.create(review: "Exceeds expectations, brings unmatched enthusiasm to the project" , rating: 5, author_id: 1, subject_id: 2)
Evaluation.create(review: "Excellent attention to detail with an eye for design", rating: 5, author_id: 1, subject_id: 3)
Evaluation.create(review: "Compassionate, consistently brought 110 percent to every aspect of project", rating: 5, author_id: 2, subject_id: 2)
Evaluation.create(review: "Thorough and logical, an exceptional problem solver", rating: 5, author_id: 4, subject_id: 2)
Evaluation.create(review: "Has a big ol' beard", rating: 5, author_id: 1, subject_id: 4)


# Generic tokens for boots
("a".."z").to_a.each do |letter|
	Token.create(characters: letter)
end

# Super tokens for admin privs
(1..9).to_a.each do |number|
	Token.create(characters: number, admin_status: true)
end

# HR rep tokens for specific companies
(1..10).to_a.each do |number|
	Token.create(characters: "hello" + number.to_s, company_id: number)
end


# Favorite sample
Favorite.create(user_id: 1, job_id: 1)

# Add impression views for profile

6.times do |id|
	Impression.create(user_id: (id + 1), created_at: Time.now - 1.day)
	Impression.create(user_id: (id + 1), created_at: Time.now - 1.day)
	Impression.create(user_id: (id + 1), created_at: Time.now + 1.day)
	Impression.create(user_id: (id + 1), created_at: Time.now - 7.day)
	Impression.create(user_id: (id + 1), created_at: Time.now - 7.day)
	Impression.create(user_id: (id + 1), created_at: Time.now - 5.day)
	Impression.create(user_id: (id + 1), created_at: Time.now - 2.day)
	Impression.create(user_id: (id + 1), created_at: Time.now - 1.day)
	Impression.create(user_id: (id + 1), created_at: Time.now - 8.day)
	Impression.create(user_id: (id + 1), created_at: Time.now + 3.day)
	Impression.create(user_id: (id + 1), created_at: Time.now - 1.day)
	Impression.create(user_id: (id + 1), created_at: Time.now + 4.day)
end















